"use client"

import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { ArrowRight, Code2 } from "lucide-react"

interface ExamplesSectionProps {
  language: "en" | "zh"
}

const translations = {
  en: {
    title: "See what others are building",
    subtitle: "Get inspired by apps generated by our community",
    tryIt: "Try this prompt",
    examples: [
      {
        prompt: "Create a modern todo list with dark mode and categories",
        tags: ["React", "TypeScript", "Tailwind"],
        preview: "/todo-app-dark-mode.jpg",
      },
      {
        prompt: "Build a weather dashboard with city search and 5-day forecast",
        tags: ["Next.js", "API", "Charts"],
        preview: "/weather-dashboard.png",
      },
      {
        prompt: "Design a landing page for a SaaS product with pricing tiers",
        tags: ["Landing Page", "Responsive", "Modern"],
        preview: "/saas-landing-page.png",
      },
    ],
  },
  zh: {
    title: "看看其他人在构建什么",
    subtitle: "从我们社区生成的应用中获得灵感",
    tryIt: "试试这个提示",
    examples: [
      {
        prompt: "创建一个带深色模式和分类的现代待办事项列表",
        tags: ["React", "TypeScript", "Tailwind"],
        preview: "/todo-app-dark-mode.jpg",
      },
      {
        prompt: "构建一个带城市搜索和 5 天预报的天气仪表板",
        tags: ["Next.js", "API", "图表"],
        preview: "/weather-dashboard.png",
      },
      {
        prompt: "为 SaaS 产品设计一个带定价层级的落地页",
        tags: ["落地页", "响应式", "现代"],
        preview: "/saas-landing-page.png",
      },
    ],
  },
}

export function ExamplesSection({ language }: ExamplesSectionProps) {
  const t = translations[language]

  return (
    <section id="examples" className="py-24 md:py-32 bg-secondary/30">
      <div className="container">
        <div className="mx-auto max-w-2xl text-center mb-16">
          <h2 className="text-4xl font-bold mb-4 text-balance">{t.title}</h2>
          <p className="text-lg text-muted-foreground text-balance">{t.subtitle}</p>
        </div>

        <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
          {t.examples.map((example, index) => (
            <Card
              key={index}
              className="group overflow-hidden border-border bg-card transition-all hover:border-accent/50 hover:shadow-lg hover:shadow-accent/5"
            >
              <div className="aspect-video overflow-hidden bg-secondary">
                <img
                  src={example.preview || "/placeholder.svg"}
                  alt={example.prompt}
                  className="h-full w-full object-cover transition-transform group-hover:scale-105"
                />
              </div>
              <div className="p-6">
                <div className="mb-4 flex items-start gap-2">
                  <Code2 className="h-5 w-5 text-accent mt-0.5 flex-shrink-0" />
                  <p className="text-sm leading-relaxed">{example.prompt}</p>
                </div>
                <div className="mb-4 flex flex-wrap gap-2">
                  {example.tags.map((tag, tagIndex) => (
                    <span
                      key={tagIndex}
                      className="rounded-full bg-accent/10 px-3 py-1 text-xs font-medium text-accent"
                    >
                      {tag}
                    </span>
                  ))}
                </div>
                <Button variant="ghost" size="sm" className="w-full group/btn">
                  {t.tryIt}
                  <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover/btn:translate-x-1" />
                </Button>
              </div>
            </Card>
          ))}
        </div>
      </div>
    </section>
  )
}
