import JSZip from 'jszip'
import type { GeneratedProject } from './code-generator'

export function downloadAsZip(project: GeneratedProject) {
  // Fallback to text file if JSZip fails
  downloadAsTextFile(project)
}

export async function downloadAsProperZip(project: GeneratedProject) {
  try {
    const zip = new JSZip()
    
    // Create directory structure and add files
    Object.entries(project.files).forEach(([filePath, content]) => {
      zip.file(filePath, content)
    })
    
    // Generate the ZIP file
    const zipBlob = await zip.generateAsync({ type: 'blob' })
    
    // Create download link
    const url = URL.createObjectURL(zipBlob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${project.projectName}.zip`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    
    console.log(`Downloaded ${project.projectName}.zip with ${Object.keys(project.files).length} files`)
  } catch (error) {
    console.error('Error creating ZIP:', error)
    // Fallback to text file
    downloadAsTextFile(project)
  }
}

function downloadAsTextFile(project: GeneratedProject) {
  // Create a simple text representation for download
  const filesContent = Object.entries(project.files)
    .map(([path, content]) => {
      const separator = '='.repeat(60)
      return `${separator}\nFile: ${path}\n${separator}\n\n${content}\n\n`
    })
    .join('\n')

  const fullContent = `PROJECT: ${project.projectName}
Generated by mornFront - mornhub.dev

INSTALLATION INSTRUCTIONS:
1. Create a new directory: mkdir ${project.projectName}
2. Navigate to it: cd ${project.projectName}
3. Create each file below with its content
4. Run: npm install
5. Run: npm run dev

${'='.repeat(80)}

${filesContent}
${'='.repeat(80)}

To use this properly:
- Copy each file section above into the respective file path
- Make sure directory structures are created (e.g., src/)
- Run npm install to install all dependencies
- Run npm run dev to start the development server

Thank you for using mornFront!
Visit: https://mornhub.dev
`

  // Create blob and download
  const blob = new Blob([fullContent], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${project.projectName}.txt`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

